# Generated by Django 5.0.2 on 2024-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to='https://api.designartproject.ru/images/100x100-01.jpg'),
        ),
    ]
